import { Injectable, OnModuleInit, OnModuleDestroy, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { LoggerService } from './logger.service';
import { CryptoService } from './crypto.service';
import { ErrorHandlerService } from './error-handler.service';
import { 
  TelegramUnifiedSDKConfig, 
  TelegramUnifiedResponse, 
  TelegramEventOptions,
  UnifiedSDKServiceStatus 
} from '../interfaces/unified-sdk.interfaces';
import { ActivityEventDto } from '../dto/event.dto';

// Import local Unified SDK
import { UnifiedSDK } from '../unified-sdk/src/UnifiedSDK';
import { UnifiedSDKError, ValidationError, UnifiedSDKConfig } from '../unified-sdk/src/types';

@Injectable()
export class UnifiedSdkService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(UnifiedSdkService.name);
  private unifiedSdk: UnifiedSDK;
  private sdkConfig: UnifiedSDKConfig;
  private initialized: boolean = false;
  private healthCheckInterval: NodeJS.Timeout;
  private statusMetrics = {
    errorCount: 0,
    successCount: 0,
    totalResponseTime: 0,
    lastHealthCheck: new Date(),
  };

  constructor(
    private configService: ConfigService,
    private loggerService: LoggerService,
    private cryptoService: CryptoService,
    private errorHandler: ErrorHandlerService,
  ) {
    this.buildSdkConfiguration();
  }

  async onModuleInit(): Promise<void> {
    try {
      await this.initializeUnifiedSdk();
      this.startHealthChecks();
    } catch (error) {
      this.logger.error('Failed to initialize Unified SDK', error);
      throw error;
    }
  }

  async onModuleDestroy(): Promise<void> {
    if (this.healthCheckInterval) {
      clearInterval(this.healthCheckInterval);
    }
    
    if (this.unifiedSdk) {
      try {
        await this.unifiedSdk.cleanup();
        this.logger.log('Unified SDK cleanup completed');
      } catch (error) {
        this.logger.error('Error during Unified SDK cleanup', error);
      }
    }
  }

  private buildSdkConfiguration(): void {
    // Use simple string keys for DDC signer (will be generated by the SDK)
    this.sdkConfig = {
      ddcConfig: {
        signer: '//Alice',
        bucketId: BigInt(0),
        network: 'testnet',
      },
      activityConfig: {
        endpoint: this.configService.get<string>('event.serviceUrl', 'https://api.stats.cere.network'),
        keyringUri: this.configService.get<string>('event.keyringUri', '//Alice'),
        appId: this.configService.get<string>('event.appId', 'telegram-bot'),
        connectionId: this.configService.get<string>('event.connectionId'),
        sessionId: this.configService.get<string>('event.sessionId'),
        appPubKey: this.configService.get<string>('event.userPubKey'),
        dataServicePubKey: this.configService.get<string>('event.dataServiceId'),
      },

      processing: {
        enableBatching: this.configService.get<boolean>('unified.enableBatching', true),
        defaultBatchSize: this.configService.get<number>('unified.defaultBatchSize', 100),
        defaultBatchTimeout: this.configService.get<number>('unified.defaultBatchTimeout', 5000),
        maxRetries: this.configService.get<number>('unified.maxRetries', 3),
        retryDelay: this.configService.get<number>('unified.retryDelay', 1000),
      },

      logging: {
        level: this.configService.get<'debug' | 'info' | 'warn' | 'error'>('unified.logLevel', 'info'),
        enableMetrics: this.configService.get<boolean>('unified.enableMetrics', true),
      },
    };
  }

  private async initializeUnifiedSdk(): Promise<void> {
    this.logger.log('Initializing Unified SDK with configuration', {
      activityEndpoint: this.sdkConfig.activityConfig?.endpoint,
      batchingEnabled: this.sdkConfig.processing.enableBatching,
    });

    try {
      this.unifiedSdk = new UnifiedSDK(this.sdkConfig);
      await this.unifiedSdk.initialize();
      this.initialized = true;

      this.logger.log('Unified SDK initialized successfully');
    } catch (error) {
      this.logger.error('Failed to initialize Unified SDK', error);
      throw error;
    }
  }

  async sendTelegramEvent(
    event: ActivityEventDto,
    options?: TelegramEventOptions
  ): Promise<TelegramUnifiedResponse> {
    if (!this.initialized) {
      throw new Error('Unified SDK not initialized');
    }

    const startTime = Date.now();

    try {
      // Transform ActivityEventDto to Telegram event format for Unified SDK
      const telegramEventPayload = {
        eventType: event.event_type,
        userId: event.account_id,
        chatId: event.payload.group_id,
        eventData: event.payload,
        timestamp: new Date(event.timestamp),
        messageId: event.payload.message_id,
        messageType: 'text', // Default message type
      };

      // Create metadata for processing
      const metadata = {
        source: 'telegram-bot',
        eventType: event.event_type,
        accountId: event.account_id,
        traceId: `telegram-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        ...options?.metadata,
      };

      this.logger.debug('Sending Telegram event to Unified SDK', {
        traceId: metadata.traceId,
        eventType: event.event_type,
        accountId: event.account_id,
        writeMode: options?.writeMode || 'realtime',
      });

      const result = await this.unifiedSdk.writeData(telegramEventPayload, {
        priority: options?.priority || 'normal',
        encryption: options?.encryption || false,
        writeMode: options?.writeMode || 'realtime',
        metadata,
      });

      const processingTime = Date.now() - startTime;
      this.statusMetrics.successCount++;
      this.statusMetrics.totalResponseTime += processingTime;

      const response: TelegramUnifiedResponse = {
        ...result,
        telegramMetadata: {
          messageId: event.payload.message_id,
          chatId: event.payload.group_id,
          userId: event.account_id,
          messageType: 'text',
          processingMode: options?.writeMode || 'realtime',
          deduplicationApplied: false, // Simplified for now
        },
      };

      this.logger.log('Telegram event processed successfully', {
        transactionId: result.transactionId,
        status: result.status,
        processingTime,
      });

      return response;
    } catch (error) {
      const processingTime = Date.now() - startTime;
      this.statusMetrics.errorCount++;
      this.statusMetrics.totalResponseTime += processingTime;

      this.logger.error('Failed to send Telegram event', error);
      throw error;
    }
  }

  async getSystemHealth(): Promise<UnifiedSDKServiceStatus> {
    try {
      const averageResponseTime = this.statusMetrics.successCount > 0 
        ? this.statusMetrics.totalResponseTime / this.statusMetrics.successCount 
        : 0;
      
      return {
        initialized: this.initialized,
        connectionStatus: {
          
          activitySDK: this.initialized ? 'connected' : 'not_configured',
        },
        lastHealthCheck: this.statusMetrics.lastHealthCheck,
        errorCount: this.statusMetrics.errorCount,
        successCount: this.statusMetrics.successCount,
        averageResponseTime,
        components: {
          rulesInterpreter: this.initialized,
          dispatcher: this.initialized,
          orchestrator: this.initialized,
        },
      };
    } catch (error) {
      this.logger.error('Health check failed', error);
      return {
        initialized: false,
        connectionStatus: {
          
          activitySDK: 'error',
        },
        lastHealthCheck: this.statusMetrics.lastHealthCheck,
        errorCount: this.statusMetrics.errorCount,
        successCount: this.statusMetrics.successCount,
        averageResponseTime: 0,
        components: {
          rulesInterpreter: false,
          dispatcher: false,
          orchestrator: false,
        },
      };
    }
  }

  private startHealthChecks(): void {
    const interval = this.configService.get<number>('unified.healthCheckInterval', 30000);
    this.healthCheckInterval = setInterval(async () => {
      try {
        this.statusMetrics.lastHealthCheck = new Date();
      } catch (error) {
        this.logger.error('Health check failed', error);
      }
    }, interval);
  }

  isInitialized(): boolean {
    return this.initialized;
  }
} 