quarkus:
  rest-client:
    tg-bot-api:
      url: 'https://api.telegram.org/bot${telegram.bot.token}'
    ton-api:
      url: '${ton.api.url}'
  kotlin-serialization:
    json:
      encode-defaults: false
      ignore-unknown-keys: true
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      origins: '*'
  datasource:
    db-kind: 'postgresql'
    devservices:
      port: 5432
  cache:
    caffeine:
      initial-capacity: 10000
      maximum-size: 10000
  flyway:
    migrate-at-start: false
    baseline-on-migrate: true
  hibernate-orm:
    log:
      sql: true
    sql-load-script: 'import.sql'
    database:
      generation: 'update'
"%dev":
  quarkus:
    rest-client:
      logging:
        scope: 'request-response'
        body-limit: 10000
    log:
      category:
        "org.jboss.resteasy.reactive.client.logging":
          level: 'DEBUG'
"%prod":
  quarkus:
    hibernate-orm:
      log:
        sql: false
      sql-load-script: 'no-file'