quarkus:
  rest-client:
    tg-bot-api:
      url: 'https://api.telegram.org/bot${telegram.bot.token}'
    activity-sdk-api:
      url: '${event.service.url}'
  kotlin-serialization:
    json:
      encode-defaults: false
      ignore-unknown-keys: true
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      origins: '*'
event:
  service:
    url: 'https://ai-event.stage.cere.io'
  app:
    id: '${EVENT_APP_ID}'
  account:
    id: '${EVENT_ACCOUNT_ID}'
  signature: '${EVENT_SIGNATURE}'
  id: '${EVENT_ID}'
  type: '${EVENT_TYPE}'
  timestamp: '${EVENT_TIMESTAMP}'
  data:
    service:
      id: '${EVENT_DATA_SERVICE_ID}'
  user:
    pub:
      key: '${EVENT_USER_PUB_KEY}'

"%dev":
  quarkus:
    rest-client:
      logging:
        scope: 'request-response'
        body-limit: 10000
    log:
      category:
        "org.jboss.resteasy.reactive.client.logging":
          level: 'DEBUG'