name: Release to stage
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: Cere-IO/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      runs-on: '["self-hosted", "cere-io-large"]'
      environment: stg
      aws_account_id: ${{ vars.DEV_CORE_AWS_ACCOUNT_ID }}
      repository: telegram-app-bot
      file: ./Dockerfile
    secrets: inherit
